---
- hosts: localhost
  tasks:
  - name: create a file via ssh connection
    file:
      dest: /tmp/ssh-created
      state: touch


- hosts: localhost
  connection: local

  tasks:
  - name: create a file via direct local connection
    file:
      dest: /tmp/direct-created
      state: touch
