- hosts: localhost
  gather_facts: no
  vars:
    dir: "./"
    droplet_name: demo

  tasks:
    - name: Create droplet dir
      file:
        path: "{{ dir }}/{{ droplet_name }}"
        owner: vagrant
        group: vagrant
        mode: '0700'
        state: directory

    - name: Create infra
      template:
        src: "{{ droplet_dir }}/drops/{{droplet_name}}/infra.tf"
        dest: "{{ dir }}/{{ droplet_name }}/infra.tf"
        owner: vagrant
        group: vagrant
        mode: '0644'