- hosts: localhost
  become: yes
  become_method: sudo
  any_errors_fatal: true
  max_fail_percentage: 0
  vars:
    swap_file_path: "/mnt/swap"
    swap_file_size_mb: 8000
    
  tasks:
    - name: Swap on
      block:
        - name: Create swap file
          command: "fallocate -l {{ swap_file_size_mb }}m {{ swap_file_path }}"
          args:
            creates: "{{ swap_file_path }}"

        - name: Change swap file permissions
          file: 
            path: "{{ swap_file_path }}"
            owner: root
            group: root
            mode: 0600
        
        - name: Check swap file type
          command: "file {{ swap_file_path }}"
          register: swapfile

        - name: Make swap file
          command: "mkswap {{ swap_file_path }}"
          when: swapfile.stdout.find('swap file') == -1
  
        - name: Write swap entry in fstab
          mount: 
            name: none
            src: "{{ swap_file_path }}"
            fstype: swap
            opts: sw
            passno: "0"
            dump: "0"
            state: present

        - name: Mount swap
          command: "swapon {{ swap_file_path }}"
          when: ansible_swaptotal_mb < 2000

        - name: sysctl changes
          sysctl:
            name: "{{ item.name }}"
            value: "{{ item.value }}"
            reload: yes
            ignoreerrors: yes
          loop:
            - { name: vm.swappiness, value: 20 }
            - { name: vm.vfs_cache_pressure, value: 10 }
      tags: 
        - "on"

    - name: Swap off
      block:
        - name: sysctl changes
          sysctl:
            name: "{{ item.name }}"
            value: "{{ item.value }}"
            reload: yes
            ignoreerrors: yes
            state: absent
          loop:
            - { name: vm.swappiness, value: 20 }
            - { name: vm.vfs_cache_pressure, value: 10 }

        - name: Remove swap entry in fstab
          mount: 
            name: none
            src: "{{ swap_file_path }}"
            fstype: swap
            opts: sw
            passno: "0"
            dump: "0"
            state: absent

        - name: Unmount swap
          command: "swapoff {{ swap_file_path }}"
          when: ansible_swaptotal_mb > 2000

        - name: Delete swap file
          file: 
            path: "{{ swap_file_path }}"
            state: absent
      tags: 
        - "off"
